import { useCallback, useEffect, useState } from 'react';
import {
  RefreshControl,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import * as Privacy from 'expo-print';
import * as Sharing from 'expo-sharing';
import { getDaySummary, getWeekSummary, getStreak, getAnchor, getWeightedAdherenceScore } from '../db/queries';
import type { DaySummary } from '../types';

const WEEKDAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

function todayDayIndex(): number {
  return ((new Date().getDay() + 6) % 7);
}

function getBoxColor(compliancePct: number, totalDoses: number) {
  if (totalDoses === 0) return '#333333';
  if (compliancePct >= 80) return '#22c55e';
  if (compliancePct >= 50) return '#eab308';
  return '#ef4444';
}

function getComplianceColor(compliancePct: number) {
  if (compliancePct >= 80) return '#22c55e';
  if (compliancePct >= 50) return '#eab308';
  return '#ef4444';
}

function formatDate(d: Date): string {
  return d.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });
}

export default function SummaryScreen() {
  const [summary, setSummary] = useState<DaySummary | null>(null);
  const [weekData, setWeekData] = useState<{ date: string; compliancePct: number; totalDoses: number; waterMl: number }[]>([]);
  const [refreshing, setRefreshing] = useState(false);
  const [streak, setStreak] = useState(0);
  const [adherenceScore, setAdherenceScore] = useState(0);
  const [sharing, setSharing] = useState(false);

  const loadData = useCallback(async () => {
    const daySummary = await getDaySummary();
    setSummary(daySummary);
    const s = await getStreak();
    setStreak(s);
    const score = await getWeightedAdherenceScore(14);
    setAdherenceScore(score);

    const week = await getWeekSummary();
    const enriched = await Promise.all(
      week.map(async (d) => {
        const full = await getDaySummary(d.date);
        const anchor = await getAnchor(d.date);
        return { ...d, totalDoses: full.totalDoses, waterMl: anchor?.water_ml ?? 0 };
      }),
    );
    setWeekData(enriched);
  }, []);

  useEffect(() => {
    loadData();
  }, [loadData]);

  const onRefresh = async () => {
    setRefreshing(true);
    await loadData();
    setRefreshing(false);
  };

  const handleShareWeek = async () => {
    setSharing(true);
    try {
      const now = new Date();
      const weekStart = new Date(now);
      weekStart.setDate(now.getDate() - 6);
      const rows = weekData.map((d, i) => {
        const date = new Date(d.date + 'T00:00:00');
        const dayName = WEEKDAYS[i];
        return `<tr style="border-bottom:1px solid #2a2a2a">
          <td style="padding:8px;color:#fff">${WEEKDAYS[(todayDayIndex() - 6 + i + 7) % 7]}</td>
          <td style="padding:8px;color:${getComplianceColor(d.compliancePct)}">${d.compliancePct}%</td>
          <td style="padding:8px;color:#fff">${d.totalDoses}</td>
          <td style="padding:8px;color:#fff">${d.waterMl}ml</td>
        </tr>`;
      }).join('');
      const html = `<html><body style="background:#0d0d0d;padding:24px;font-family:sans-serif">
        <h1 style="color:#22c55e;font-size:18px">Coimbra Protocol — Weekly Report</h1>
        <p style="color:#888;font-size:13px">${formatDate(weekStart)} — ${formatDate(now)}</p>
        <table style="width:100%;border-collapse:collapse;font-size:13px">
          <tr style="background:#1a1a1a"><th style="padding:8px;text-align:left;color:#888">Day</th><th style="padding:8px;text-align:left;color:#888">Compliance</th><th style="padding:8px;text-align:left;color:#888">Doses</th><th style="padding:8px;text-align:left;color:#888">Water</th></tr>
          ${rows}
        </table>
        <p style="color:#555;font-size:11px;margin-top:24px;text-align:center">Generated by Coimbra Protocol App</p>
      </body></html>`;
      const { uri } = await Privacy.printToFileAsync({ html });
      await Sharing.shareAsync(uri, { mimeType: 'application/pdf' });
    } finally {
      setSharing(false);
    }
  };

  const taken = summary?.takenDoses ?? 0;
  const total = summary?.totalDoses ?? 0;
  const compliancePct = summary?.compliancePct ?? 0;
  const waterMl = summary?.waterMl ?? 0;
  const ringColor = getComplianceColor(compliancePct);
  const maxBarHeight = 120;
  const waterGoal = 2500;

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={styles.content}
      showsVerticalScrollIndicator={false}
      refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor="#22c55e" />}
    >
      <Text style={styles.heading}>Summary</Text>

      <View style={styles.statRow}>
        <View style={styles.statCard}>
          <Text style={styles.statValue}>{taken}/{total}</Text>
          <Text style={styles.statLabel}>Doses Taken</Text>
        </View>
        <View style={styles.statCard}>
          <Text style={styles.statValue}>{waterMl}</Text>
          <Text style={styles.statLabel}>Water (ml)</Text>
        </View>
      </View>

      {/* Compliance Ring Card */}
      <View style={styles.complianceCard}>
        <Text style={styles.cardDayLabel}>Today</Text>
        <View style={styles.ringContainer}>
          <View style={[styles.ringOuter, { borderColor: '#2a2a2a' }]}>
            <View style={[styles.ringInnerAccent, { borderColor: ringColor }]} />
            <View style={styles.ringCenter}>
              <Text style={[styles.ringNumber, { color: ringColor }]}>{compliancePct}</Text>
              <Text style={styles.ringPercent}>%</Text>
            </View>
          </View>
        </View>
        <Text style={styles.complianceLabel}>Compliance</Text>
        <View style={styles.barBg}>
          <View style={[styles.barFill, { width: `${Math.min(compliancePct, 100)}%` as `${number}%`, backgroundColor: ringColor }]} />
        </View>
      </View>

      {/* Protocol Score */}
      <View style={styles.scoreCard}>
        <Text style={styles.scoreValue}>{adherenceScore}</Text>
        <Text style={styles.scoreLabel}>Protocol Score</Text>
        <Text style={styles.scoreSub}>Weighted for recency and supplement priority</Text>
      </View>

      {/* Streak Card */}
      <View style={styles.streakCard}>
        <Text style={styles.streakValue}>{streak === 0 ? '—' : `${streak}`}{streak >= 3 ? ' 🔥' : ''}</Text>
        <Text style={[styles.streakLabel, streak === 0 ? styles.streakNoData : null]}>{streak === 0 ? 'no streak yet' : 'day streak'}</Text>
      </View>

      {/* Water This Week */}
      <Text style={styles.sectionTitle}>Water This Week</Text>
      <View style={styles.waterChartRow}>
        {weekData.map((d, i) => {
          const barHeight = Math.min((d.waterMl / waterGoal) * maxBarHeight, maxBarHeight);
          const dayName = WEEKDAYS[(todayDayIndex() - 6 + i + 7) % 7];
          return (
            <View key={d.date} style={styles.waterCol}>
              <Text style={styles.waterMlLabel}>{d.waterMl > 0 ? `${Math.round(d.waterMl / 100) * 100}` : ''}</Text>
              <View style={styles.waterBarTrack}>
                <View style={[styles.waterBarFill, { height: `${barHeight}%` as `${number}%`, backgroundColor: '#3b82f6' }]} />
                <View style={[styles.waterBarRemain, { height: `${maxBarHeight - barHeight}%` as `${number}%` }]} />
              </View>
              <View style={styles.goalDash}>
                <View style={styles.goalDashSeg} />
                <View style={styles.goalDashSegTrans} />
                <View style={styles.goalDashSeg} />
                <View style={styles.goalDashSegTrans} />
                <View style={styles.goalDashSeg} />
              </View>
              <Text style={styles.waterDayLabel}>{dayName}</Text>
            </View>
          );
        })}
      </View>

      {/* Week compliance boxes */}
      <Text style={styles.sectionTitle}>This Week</Text>
      <View style={styles.weekRow}>
        {weekData.map((d, i) => {
          const isToday = i === todayDayIndex();
          return (
            <View key={d.date} style={styles.dayCol}>
              <View style={[styles.dayBox, { backgroundColor: getBoxColor(d.compliancePct, d.totalDoses) }, isToday ? styles.dayBoxToday : null]} />
              <Text style={[styles.dayLabel, isToday ? styles.dayLabelToday : null]}>{WEEKDAYS[i]}</Text>
            </View>
          );
        })}
      </View>

      {/* Share Week button */}
      <TouchableOpacity style={[styles.shareButton, sharing ? styles.shareButtonDisabled : null]} onPress={handleShareWeek} disabled={sharing} activeOpacity={0.8}>
        <Text style={styles.shareButtonText}>{sharing ? 'Sharing...' : 'Share Week Report'}</Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0d0d0d' },
  content: { paddingTop: 60, paddingHorizontal: 20, paddingBottom: 40 },
  heading: { color: '#ffffff', fontSize: 22, fontWeight: '700', marginBottom: 24 },
  statRow: { flexDirection: 'row', gap: 12, marginBottom: 16 },
  statCard: { flex: 1, backgroundColor: '#1a1a1a', borderRadius: 12, padding: 20, alignItems: 'center' },
  statValue: { color: '#ffffff', fontSize: 32, fontWeight: '800' },
  statLabel: { color: '#888888', fontSize: 13, marginTop: 4 },
  complianceCard: { backgroundColor: '#1a1a1a', borderRadius: 12, padding: 20, alignItems: 'center', marginBottom: 16 },
  cardDayLabel: { color: '#888888', fontSize: 12, fontWeight: '600', letterSpacing: 1, textTransform: 'uppercase', marginBottom: 16 },
  ringContainer: { marginBottom: 8 },
  ringOuter: { width: 120, height: 120, borderRadius: 60, borderWidth: 8, alignItems: 'center', justifyContent: 'center', position: 'relative' },
  ringInnerAccent: { position: 'absolute', width: 120, height: 120, borderRadius: 60, borderWidth: 8, borderTopColor: 'transparent', borderRightColor: 'transparent', borderBottomColor: 'transparent', transform: [{ rotate: '-45deg' }] },
  ringCenter: { flexDirection: 'row', alignItems: 'flex-end' },
  ringNumber: { fontSize: 36, fontWeight: '800', lineHeight: 40 },
  ringPercent: { color: '#888888', fontSize: 14, fontWeight: '600', marginBottom: 4 },
  complianceLabel: { color: '#888888', fontSize: 13, marginTop: 4, marginBottom: 16 },
  barBg: { width: '100%', height: 6, backgroundColor: '#2a2a2a', borderRadius: 3, overflow: 'hidden' },
  barFill: { height: '100%', borderRadius: 3 },
  scoreCard: { backgroundColor: '#1a1a1a', borderRadius: 12, padding: 20, alignItems: 'center', marginBottom: 16 },
  scoreValue: { color: '#22c55e', fontSize: 32, fontWeight: '800' },
  scoreLabel: { color: '#ffffff', fontSize: 14, fontWeight: '600', marginTop: 4 },
  scoreSub: { color: '#555555', fontSize: 11, marginTop: 4 },
  streakCard: { backgroundColor: '#1a1a1a', borderRadius: 12, padding: 20, alignItems: 'center', marginBottom: 24 },
  streakValue: { color: '#22c55e', fontSize: 32, fontWeight: '800' },
  streakLabel: { color: '#888888', fontSize: 13, marginTop: 4 },
  streakNoData: { color: '#555555' },
  waterChartRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 24, paddingHorizontal: 4 },
  waterCol: { alignItems: 'center', gap: 4, flex: 1 },
  waterMlLabel: { color: '#555555', fontSize: 9, height: 14 },
  waterBarTrack: { width: 16, height: 120, backgroundColor: '#2a2a2a', borderRadius: 4, overflow: 'hidden', justifyContent: 'flex-end' },
  waterBarFill: { width: '100%', borderRadius: 4, position: 'absolute', bottom: 0 },
  waterBarRemain: { width: '100%', backgroundColor: 'transparent' },
  goalDash: { height: 12, width: 16, alignItems: 'center', justifyContent: 'space-between' },
  goalDashSeg: { width: 10, height: 2, backgroundColor: '#3b82f644' },
  goalDashSegTrans: { width: 10, height: 2, backgroundColor: 'transparent' },
  waterDayLabel: { color: '#888888', fontSize: 10, fontWeight: '600' },
  sectionTitle: { color: '#ffffff', fontSize: 16, fontWeight: '600', marginBottom: 12 },
  weekRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
  dayCol: { alignItems: 'center', gap: 6 },
  dayBox: { width: 36, height: 36, borderRadius: 8 },
  dayBoxToday: { borderWidth: 2, borderColor: '#ffffff' },
  dayLabel: { color: '#888888', fontSize: 11, fontWeight: '600' },
  dayLabelToday: { color: '#ffffff' },
  shareButton: { backgroundColor: '#22c55e', borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  shareButtonDisabled: { opacity: 0.4 },
  shareButtonText: { color: '#0d0d0d', fontSize: 16, fontWeight: '800' },
});
