import * as Print from 'expo-print';
import { getDaySummary, getStreak, getRelapseEvents, todayStr } from '../db/queries';

function getBoxColor(pct: number, total: number): string {
  if (total === 0) return '#2a2a2a';
  if (pct >= 80) return '#22c55e';
  if (pct >= 50) return '#eab308';
  return '#ef4444';
}

export async function generateComplianceReport(
  patientName: string,
  weightKg: number,
  d3Dose: string
): Promise<string> {
  const days: string[] = [];
  for (let i = 29; i >= 0; i--) {
    const d = new Date();
    d.setDate(d.getDate() - i);
    days.push(d.toISOString().split('T')[0]);
  }

  let totalTaken = 0;
  let totalMissed = 0;
  let bestDayPct = 0;
  const rows: string[] = [];

  for (const dateStr of days) {
    const summary = await getDaySummary(dateStr);
    totalTaken += summary.takenDoses;
    totalMissed += summary.missedDoses;
    if (summary.compliancePct > bestDayPct) bestDayPct = summary.compliancePct;

    const color = getBoxColor(summary.compliancePct, summary.totalDoses);
    rows.push(`<td style="background:${color};text-align:center;padding:6px;font-size:11px;color:${color === '#2a2a2a' ? '#666' : '#0d0d0d'};font-weight:700;border-radius:4px">${new Date(dateStr).getDate()}</td>`);
  }

  const weeklyRows: string[] = [];
  for (let i = 0; i < rows.length; i += 7) {
    weeklyRows.push(`<tr>${rows.slice(i, i + 7).join('')}</tr>`);
  }

  const streak = await getStreak();
  const events = await getRelapseEvents();

  const relapseHtml = events.length > 0 ? `
    <h2 style="color:#ef4444;font-size:16px;margin-top:24px">Relapse Events</h2>
    <table style="width:100%;border-collapse:collapse;font-size:12px">
      <tr style="background:#1a1a1a;color:#fff">
        <th style="padding:8px;text-align:left">Date</th>
        <th style="padding:8px;text-align:left">Type</th>
        <th style="padding:8px;text-align:left">Severity</th>
        <th style="padding:8px;text-align:left">Notes</th>
      </tr>
      ${events.map(e => `
        <tr style="border-bottom:1px solid #2a2a2a">
          <td style="padding:6px">${e.date}</td>
          <td style="padding:6px">${e.type}</td>
          <td style="padding:6px">${e.severity ?? '—'}</td>
          <td style="padding:6px">${e.notes || '—'}</td>
        </tr>
      `).join('')}
    </table>
  ` : '';

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        body { font-family: -apple-system, sans-serif; background: #0d0d0d; color: #ffffff; padding: 24px; margin: 0; }
        h1 { color: #22c55e; font-size: 20px; margin-bottom: 4px; }
        .sub { color: #888888; font-size: 13px; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; }
      </style>
    </head>
    <body>
      <h1>Coimbra Protocol — Compliance Report</h1>
      <div class="sub">
        <p>Patient: ${patientName} | Weight: ${weightKg}kg | D3 Dose: ${d3Dose} IU</p>
        <p>Generated: ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
      </div>

      <h2 style="color:#22c55e;font-size:16px">30-Day Compliance Calendar</h2>
      <table style="width:100%;border-collapse:separate;border-spacing:3px">
        ${weeklyRows.join('')}
      </table>

      <h2 style="color:#22c55e;font-size:16px;margin-top:24px">Stats</h2>
      <table style="width:100%;border-collapse:collapse;font-size:13px">
        <tr style="border-bottom:1px solid #2a2a2a"><td style="padding:8px;color:#888">Current Streak</td><td style="padding:8px;font-weight:700">${streak} days</td></tr>
        <tr style="border-bottom:1px solid #2a2a2a"><td style="padding:8px;color:#888">Best Day Compliance</td><td style="padding:8px;font-weight:700">${bestDayPct}%</td></tr>
        <tr style="border-bottom:1px solid #2a2a2a"><td style="padding:8px;color:#888">Total Doses Taken</td><td style="padding:8px;font-weight:700">${totalTaken}</td></tr>
        <tr style="border-bottom:1px solid #2a2a2a"><td style="padding:8px;color:#888">Total Doses Missed</td><td style="padding:8px;font-weight:700">${totalMissed}</td></tr>
      </table>

      ${relapseHtml}

      <p style="color:#555555;font-size:11px;margin-top:32px;text-align:center">
        Generated by Coimbra Protocol App v1.0 — Data stored locally on patient device
      </p>
    </body>
    </html>
  `;

  const { uri } = await Print.printToFileAsync({ html });
  return uri;
}
